#!/usr/bin/env bash
# exportcommands.sh — Export ~/.claude/ dirs to jleechanorg/claude-commands
#
# Behavior:
#   - Source files overwrite target files (rsync default)
#   - Files only in target are PRESERVED (rsync default; no --delete flag)
#   - README.md is regenerated by Claude CLI
#   - Content filters strip project-specific strings via perl -pi -e (supports \b on macOS)
#
# Usage: bash ~/.claude/commands/exportcommands.sh [--dry-run]

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────────────
TARGET_REPO="jleechanorg/claude-commands"
BRANCH="export-$(date +%Y%m%d-%H%M%S)"
REPO_DIR="$(mktemp -d)/claude-commands"

# ── Cleanup trap — remove temp dir on exit (normal or error) ────────────────
trap 'rm -rf "$(dirname "$REPO_DIR")"' EXIT
GLOBAL_CLAUDE="$HOME/.claude"
# Detect project root: honour $PROJECT_ROOT env var, then git root of current dir.
# Fail fast if git rev-parse fails — do not silently export to a bogus path.
if [[ -z "${PROJECT_ROOT:-}" ]]; then
  PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    echo "ERROR: PROJECT_ROOT is unset and git rev-parse failed. Set PROJECT_ROOT before running." >&2
    exit 1
  }
fi
PROJECT_CLAUDE="$PROJECT_ROOT/.claude"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# Dirs from ~/.claude/ → .claude/<dir> in target repo
CLAUDE_DIRS=(commands skills hooks agents scripts)

# Dirs from project root → repo root in target repo
ROOT_DIRS=(orchestration automation ralph)

# Hermes-managed surfaces — included as a SEPARATE top-level dir in the target repo
# (./hermes/skills and ./hermes/commands) so the superset covers ~/.claude/ + ~/.hermes/
# + project .claude/. The hermes-deploy-pipeline skill is the SOURCE OF TRUTH for
# hermes skills; this export ships a downstream mirror that downstream consumers
# (e.g. other machines' ~/.claude/skills) can copy from.
HERMES_DIRS=(skills commands)
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"

# Codex CLI's own dot-prefixed config dir, mirroring ~/.claude/ -> .claude/.
# Only `hooks` is exported: ~/.codex/commands and ~/.codex/skills are almost
# entirely duplicate filenames already in .claude/commands, or symlinks into
# .claude/skills, ~/.hermes/skills, other unrelated local projects, and
# third-party .tessl plugin content (not this user's own IP to redistribute).
# ~/.codex/hooks/ is genuinely unique, real Codex-specific hook scripts.
# hooks.json (the hook registration config) is copied alongside as a single
# file, not a directory, since it's small and directly documents how the
# hooks/ scripts wire into Codex CLI's own hook system.
CODEX_DIRS=(hooks)
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"

# Files to exclude from content filtering (contain literal regex patterns or are test files
# that assert on the source strings and must not have them silently replaced)
FILTER_SKIP=(exportcommands.py exportcommands.sh loc_simple.sh test_exportcommands.py)

# Shared rsync excludes — binaries, media, build artifacts, repo hygiene.
# Anything that should NEVER be in the published template regardless of source surface.
# The HERMES-specific extras (mcp config, plugin.json, package-lock.json) only apply to
# the ~/.hermes/ rsync pass; root-dir and union passes don't generate those files.
COMMON_RSYNC_EXCLUDES=(
  '*.pyc'
  '__pycache__/'
  '.DS_Store'
  '*.ttf' '*.otf' '*.woff' '*.woff2' '*.eot'
  '*.png' '*.jpg' '*.jpeg' '*.gif' '*.ico' '*.svg' '*.webp'
  '*.mp4' '*.mp3' '*.wav' '*.pdf' '*.zip' '*.tar' '*.gz'
  '*.xsd' '*.xml'
  '*.testmondata'
  '*.db' '*.sqlite' '*.sqlite3'
  'gsd-*'
  '.gsd*'
  'super.md'
  'copilotsuper.md'
  'superpowers*'
  'exportcommands.sh.bak-20260720-super-exclude'
)
HERMES_RSYNC_EXTRAS=(
  '.mcp_config*'
  'plugin.json'
  'package-lock.json'
  '.bundled_manifest'
  '.curator_backups'
)

# Emit rsync --exclude flags from an array of patterns. Used by the root-dir and
# hermes rsync passes to keep the exclude lists DRY.
# Patterns are emitted unquoted — rsync needs raw glob characters (`*`, `[`, `?`)
# in the exclude value, not shell-escaped forms. Callers must pass strings
# without spaces, which is true for every entry in COMMON_RSYNC_EXCLUDES /
# HERMES_RSYNC_EXTRAS.
rsync_excludes() {
  local _pattern
  for _pattern in "$@"; do
    printf -- '--exclude=%s ' "$_pattern"
  done
}

# Compute Hermes-side file counts for the README prompt. Kept as a single
# helper so the incremental-update and first-export README paths agree on the
# same glob (`-name 'SKILL.md'` is canonical — `find -type f` double-counts
# the `references/` etc. files inside each skill directory).
compute_hermes_counts() {
  if [[ -d "hermes/commands" ]]; then
    HERMES_COMMANDS_COUNT=$(find hermes/commands -type f 2>/dev/null | wc -l | tr -d ' ')
  else
    HERMES_COMMANDS_COUNT=0
  fi
  if [[ -d "hermes/skills" ]]; then
    HERMES_SKILLS_COUNT=$(find hermes/skills -name 'SKILL.md' 2>/dev/null | wc -l | tr -d ' ')
  else
    HERMES_SKILLS_COUNT=0
  fi
  export HERMES_COMMANDS_COUNT HERMES_SKILLS_COUNT
}

# Content filter substitutions (applied to all .md .py .sh .yml files)
# NOTE: Uses perl -pi -e for cross-platform \b word-boundary support (macOS sed lacks it)
# IMPORTANT: Specific patterns must come before general ones:
#   $GITHUB_REPOSITORY BEFORE your-project.com (general would consume specific)
declare -a SUBS=(
  's|jleechanorg/worldarchitect\.ai|\$GITHUB_REPOSITORY|g'
  's|worldarchitect\.ai|your-project.com|g'
  's|${PROJECT_NAME:-your-project}-ci|\$\{PROJECT_NAME:-your-project\}-ci|g'
  's|${PROJECT_NAME:-your-project}-automation|\$\{PROJECT_NAME:-your-project\}-automation|g'
  's|worldarchitect-chrome\.sh|\$\{PROJECT_NAME:-your-project\}-chrome.sh|g'
  's|playwright-${PROJECT_NAME:-your-project}|playwright-\$\{PROJECT_NAME:-your-project\}|g'
  's|superpowers-chrome-${PROJECT_NAME:-your-project}|superpowers-chrome-\$\{PROJECT_NAME:-your-project\}|g'
  's|$HOME|\$HOME|g'
  's|\bjleechan\b|\$USER|g'
  's|jleechantest\@gmail\.com|<your-email\@gmail.com>|g'
  's|WorldArchitect\.AI|Your Project|g'
  's|TESTING=true python|TESTING=true python|g'
  's|AIzaSy[a-zA-Z0-9_-]{33}|AIzaSy[REDACTED_GEMINI_KEY]|g'
  's|xoxp-[a-zA-Z0-9_-]{20,}|xoxp-[REDACTED_SLACK_USER_TOKEN]|g'
  's|xoxb-[a-zA-Z0-9_-]{20,}|xoxb-[REDACTED_SLACK_BOT_TOKEN]|g'
  's|xapp-[a-zA-Z0-9_-]{20,}|xapp-[REDACTED_SLACK_APP_TOKEN]|g'
  's|ghp_[a-zA-Z0-9]{36}|ghp_[REDACTED_GITHUB_TOKEN]|g'
  's|gho_[a-zA-Z0-9]{36}|gho_[REDACTED_GITHUB_TOKEN]|g'
)
# $PROJECT_ROOT/ substitution is applied separately, skipping workflow files.
# GitHub Actions does NOT expand $PROJECT_ROOT in paths: filters or hashFiles().
MVP_SITE_SUB='s|$PROJECT_ROOT/|\$PROJECT_ROOT/|g'

# ── Helpers ─────────────────────────────────────────────────────────────────
log()  { echo "  $*"; }
ok()   { echo "  ✅ $*"; }
warn() { echo "  ⚠️  $*" >&2; }

apply_filters() {
  local file="$1"
  local base; base="$(basename "$file")"
  for skip in "${FILTER_SKIP[@]}"; do
    [[ "$base" == "$skip" ]] && return 0
  done
  # Use perl -pi -e: supports \b word boundaries on macOS (BSD sed lacks \b)
  for sub in "${SUBS[@]}"; do
    perl -pi -e "$sub" "$file"
  done
  # Apply $PROJECT_ROOT/ → $PROJECT_ROOT/ only for non-workflow files.
  # GitHub Actions does NOT expand $PROJECT_ROOT in `paths:` filters or hashFiles(),
  # so substituting it into workflows/*.yml would silently break CI triggers.
  case "$file" in
    workflows/*.yml|workflows/*.yaml) ;;
    *) perl -pi -e "$MVP_SITE_SUB" "$file" ;;
  esac
}

# ── Clone & branch ──────────────────────────────────────────────────────────
echo "▶ Cloning $TARGET_REPO..."
gh repo clone "$TARGET_REPO" "$REPO_DIR" -- --depth 1
cd "$REPO_DIR"

git config user.email "claude-export@anthropic.com"
git config user.name "Claude Export"
git config commit.gpgsign false

git checkout main
git pull --ff-only origin main
git checkout -b "$BRANCH"

# ── Union-merge ~/.claude/ and .claude/ into export ──────────────────────────
# Strategy:
#   - File only in GLOBAL (~/.claude/):   use global   (came from another project/plugin)
#   - File only in PROJECT (.claude/):    use project  (worldai source)
#   - File in both, identical:            use either   (no conflict)
#   - File in both, project newer:        use project  (auto-resolve)
#   - File in both, global newer:         use global   (auto-resolve)
#   - File in both, same mtime, differ:   CONFLICT — report and use project as tiebreak
#
CONFLICTS=()   # accumulates "dir/relpath: reason" strings for any unresolved conflicts

union_dir() {
  local dir="$1"
  local global_src="$GLOBAL_CLAUDE/$dir"
  local project_src="$PROJECT_CLAUDE/$dir"
  local dst=".claude/$dir"
  mkdir -p "$dst"

  # Collect union of all relative paths from both sources
  local all_relpaths=()
  declare -A seen_relpaths=()
  while IFS= read -r -d '' f; do
    local relpath="${f#$global_src/}"
    all_relpaths+=("$relpath")
    seen_relpaths["$relpath"]=1
  done < <(find "$global_src" -type f \
    \( -not -path '*/_archive/*' \) \
    \( -not -name '*.pyc' \) \
    \( -not -name '*.pyo' \) \
    \( -not -name '.DS_Store' \) \
    \( -not -path '*/__pycache__/*' \) \
    \( -not -path '*/.ruff_cache/*' \) \
    \( -not -path '*/canvas-fonts/*' \) \
    \( -not -name '*.ttf' \) \
    \( -not -name '*.otf' \) \
    \( -not -name '*.woff' \) \
    \( -not -name '*.woff2' \) \
    \( -not -name '*.eot' \) \
    \( -not -name '*.png' \) \
    \( -not -name '*.jpg' \) \
    \( -not -name '*.jpeg' \) \
    \( -not -name '*.gif' \) \
    \( -not -name '*.ico' \) \
    \( -not -name '*.webp' \) \
    \( -not -name '*.svg' \) \
    \( -not -name '*.mp4' \) \
    \( -not -name '*.mp3' \) \
    \( -not -name '*.wav' \) \
    \( -not -name '*.pdf' \) \
    \( -not -name '*.zip' \) \
    \( -not -name '*.tar' \) \
    \( -not -name '*.gz' \) \
    \( -not -name '*.db' \) \
    \( -not -name '*.sqlite' \) \
    \( -not -name '*.sqlite3' \) \
    \( -not -name '*.xsd' \) \
    \( -not -name '*.xml' \) \
    \( -not -name '*.testmondata' \) \
    -print0 2>/dev/null || true)

  while IFS= read -r -d '' f; do
    local relpath="${f#$project_src/}"
    if [[ -z "${seen_relpaths["$relpath"]:-}" ]]; then
      all_relpaths+=("$relpath")
      seen_relpaths["$relpath"]=1
    fi
  done < <(find "$project_src" -type f \
    \( -not -name '*.pyc' \) \
    \( -not -name '.DS_Store' \) \
    \( -not -path '*/__pycache__/*' \) \
    \( -not -path '*/.ruff_cache/*' \) \
    \( -not -path '*/canvas-fonts/*' \) \
    -not -name 'exportcommands.py' \
    \( -name '*.sh' -o -name '*.py' -o -name '*.md' -o -name '*.json' \
       -o -name '*.toml' -o -name '*.yaml' -o -name '*.yml' \
       -o -name '*.js' -o -name '*.ts' -o -name '*.css' -o -name '*.html' \
       -o -name '*.cfg' -o -name '*.ini' -o -name '*.conf' \) \
    -print0 2>/dev/null || true)

  local only_global=0 only_project=0 identical=0 auto_resolved=0

  for relpath in "${all_relpaths[@]:-}"; do
    [[ -z "$relpath" ]] && continue
    local gfile="$global_src/$relpath"
    local pfile="$project_src/$relpath"
    local outfile="$dst/$relpath"
    mkdir -p "$(dirname "$outfile")"

    if [[ ! -f "$gfile" ]]; then
      # Only in project → use project
      cp "$pfile" "$outfile"
      only_project=$((only_project + 1))
    elif [[ ! -f "$pfile" ]]; then
      # Only in global → use global
      cp "$gfile" "$outfile"
      only_global=$((only_global + 1))
    elif diff -q "$gfile" "$pfile" >/dev/null 2>&1; then
      # Identical → use either
      cp "$pfile" "$outfile"
      identical=$((identical + 1))
    else
      # Both exist and differ — resolve by mtime
      local gmtime ptime
      gmtime=$(stat -c %Y "$gfile" 2>/dev/null) || gmtime=$(stat -f %m "$gfile" 2>/dev/null) || gmtime=0
      ptime=$(stat -c %Y "$pfile" 2>/dev/null) || ptime=$(stat -f %m "$pfile" 2>/dev/null) || ptime=0
      local diff_secs=$(( gmtime - ptime ))
      [[ $diff_secs -lt 0 ]] && diff_secs=$(( -diff_secs ))

      if (( diff_secs > 60 )); then
        # Clear time difference — use newer file
        if (( gmtime > ptime )); then
          cp "$gfile" "$outfile"
          log "  auto: $dir/$relpath → global (newer by $diff_secs s)"
        else
          cp "$pfile" "$outfile"
          log "  auto: $dir/$relpath → project (newer by $diff_secs s)"
        fi
        auto_resolved=$((auto_resolved + 1))
      else
        # Same-age conflict — project wins as tiebreak; flag for user
        cp "$pfile" "$outfile"
        CONFLICTS+=("$dir/$relpath: both versions differ, same mtime (±${diff_secs}s) — used project copy")
        auto_resolved=$((auto_resolved + 1))
      fi
    fi
  done

  ok "$dir (global-only:$only_global  project-only:$only_project  identical:$identical  auto-resolved:$auto_resolved)"
}

echo "▶ Union-merging ~/.claude/ + .claude/ directories..."
for dir in "${CLAUDE_DIRS[@]}"; do
  union_dir "$dir"
done

# ── Rsync root-level directories ─────────────────────────────────────────────
echo "▶ Syncing root directories..."
# shellcheck disable=SC2046
for dir in "${ROOT_DIRS[@]}"; do
  src="$PROJECT_ROOT/$dir/"
  dst="./$dir/"
  if [[ ! -d "$src" ]]; then
    warn "$dir not found at $src — skipping"
    continue
  fi
  mkdir -p "$dst"
  rsync -a $(rsync_excludes "${COMMON_RSYNC_EXCLUDES[@]}") \
    "$src" "$dst"
  ok "$dir"
done

# ── Rsync ~/.hermes/<dir> → hermes/<dir> at target repo root ─────────────────
# Source of truth: ~/projects/hermes-agent (per hermes-deploy-pipeline skill).
# These are downstream mirrors — content filters rewrite $HOME / $USER to keep
# the export portable. Missing dir = soft skip (Hermes may not be installed on
# every machine), not a hard failure.
echo "▶ Syncing ~/.hermes/ surfaces..."
# shellcheck disable=SC2046
for dir in "${HERMES_DIRS[@]}"; do
  src="$HERMES_HOME/$dir/"
  dst="./hermes/$dir/"
  if [[ ! -d "$src" ]]; then
    echo "  ⚠️ hermes/$dir not found at $src — skipping (Hermes not installed?)"
    continue
  fi
  mkdir -p "$dst"
  rsync -aL \
    $(rsync_excludes "${COMMON_RSYNC_EXCLUDES[@]}" "${HERMES_RSYNC_EXTRAS[@]}") \
    "$src" "$dst"
  echo "  ✅ hermes/$dir"
done

# ── Rsync ~/.codex/<dir> → .codex/<dir> at target repo root ──────────────────
# Deliberately NOT -L (no symlink following): ~/.codex/skills is heavily
# symlinked into .claude/skills, ~/.hermes/skills, unrelated local projects,
# and third-party .tessl plugin content — following those would duplicate
# already-exported content or redistribute someone else's IP. Missing dir =
# soft skip (Codex may not be installed on every machine), not a hard failure.
echo "▶ Syncing ~/.codex/ surfaces..."
# shellcheck disable=SC2046
for dir in "${CODEX_DIRS[@]}"; do
  src="$CODEX_HOME/$dir/"
  dst="./.codex/$dir/"
  if [[ ! -d "$src" ]]; then
    echo "  ⚠️ .codex/$dir not found at $src — skipping (Codex not installed?)"
    continue
  fi
  mkdir -p "$dst"
  rsync -a --exclude='*.bak*' --exclude='tests/' \
    $(rsync_excludes "${COMMON_RSYNC_EXCLUDES[@]}") \
    "$src" "$dst"
  echo "  ✅ .codex/$dir"
done
# hooks.json documents how .codex/hooks/*.sh|py wire into Codex CLI's hook
# system — copy it alongside hooks/ as a single file, not a directory member.
if [[ -f "$CODEX_HOME/hooks.json" ]]; then
  mkdir -p ".codex"
  cp "$CODEX_HOME/hooks.json" ".codex/hooks.json"
  echo "  ✅ .codex/hooks.json"
fi


# ── Remove files that must not be in the public template ─────────────────────
# settings.json / settings.local.json: MCP auth tokens + bypassPermissions flags (never publish)
rm -f ".claude/settings.json"
rm -f ".claude/settings.local.json"
# exportcommands.py: deprecated 2347-line Python script, contains hardcoded paths
# that cannot be filtered (it's in FILTER_SKIP to protect its regex patterns)
rm -f ".claude/commands/exportcommands.py"
# agentf-specific hooks: guard personal git identity + block push to jleechanorg.
# These encode personal account details and have no value in a shared template.
find ".claude/hooks" -name '*agentf*' -delete 2>/dev/null || true

# ── Copy GitHub workflows (examples only) ───────────────────────────────────
if [[ -d "$PROJECT_ROOT/.github/workflows" ]]; then
  mkdir -p "workflows"
  rsync -a \
    --include='*.yml' --include='*.yaml' --exclude='*' \
    "$PROJECT_ROOT/.github/workflows/" "workflows/"
  ok "workflows (examples)"
fi

echo "▶ Applying content filters & secret redactions..."
python3 -c "
import os, sys, re

subs = [
  (re.compile(r'jleechanorg/worldarchitect\.ai'), r'\$GITHUB_REPOSITORY'),
  (re.compile(r'worldarchitect\.ai'), r'your-project.com'),
  (re.compile(r'${PROJECT_NAME:-your-project}-ci'), r'\${PROJECT_NAME:-your-project}-ci'),
  (re.compile(r'${PROJECT_NAME:-your-project}-automation'), r'\${PROJECT_NAME:-your-project}-automation'),
  (re.compile(r'worldarchitect-chrome\.sh'), r'\${PROJECT_NAME:-your-project}-chrome.sh'),
  (re.compile(r'playwright-${PROJECT_NAME:-your-project}'), r'playwright-\${PROJECT_NAME:-your-project}'),
  (re.compile(r'superpowers-chrome-${PROJECT_NAME:-your-project}'), r'superpowers-chrome-\${PROJECT_NAME:-your-project}'),
  (re.compile(r'$HOME'), r'\$HOME'),
  (re.compile(r'\bjleechan\b'), r'\$USER'),
  (re.compile(r'jleechantest@gmail\.com'), r'<your-email@gmail.com>'),
  (re.compile(r'WorldArchitect\.AI'), r'Your Project'),
  (re.compile(r'TESTING=true python'), r'TESTING=true python'),
  (re.compile(r'AIzaSy[a-zA-Z0-9_-]{30,45}'), r'[REDACTED_GCP_KEY]'),
  (re.compile(r'xox[bapors]-[a-zA-Z0-9_.-]{6,}'), r'[REDACTED_SLACK_TOKEN]'),
  (re.compile(r'gh[pousr]_[a-zA-Z0-9_-]{6,}'), r'[REDACTED_GITHUB_TOKEN]'),
  (re.compile(r'eyJhbGciOiJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+'), r'[REDACTED_JWT_TOKEN]'),
  (re.compile(r'\bsk-[a-zA-Z0-9_.-]{6,}'), r'[REDACTED_OPENAI_KEY]'),
  (re.compile(r'token=[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', re.I), r'token=[REDACTED_UUID_TOKEN]'),
]
mvp_sub = (re.compile(r'$PROJECT_ROOT/'), r'\$PROJECT_ROOT/')

allowed_exts = ('.md', '.py', '.sh', '.yml', '.yaml', '.json', '.cjs', '.js', '.mjs', '.ts', '.html', '.css', '.toml')
dirs = ['.claude', '.codex', 'orchestration', 'automation', 'ralph', 'workflows', 'hermes', 'scripts', 'agents', 'commands', 'skills', 'hooks']
for d in dirs:
  if not os.path.exists(d): continue
  for root, dirs_list, files in os.walk(d, topdown=False):
    for name in files:
      filepath = os.path.join(root, name)
      is_allowed = name.endswith(allowed_exts) and not ('.bak' in name or name.endswith('.orig') or name.endswith('.log') or name.endswith('.jsonl') or name == '.bundled_manifest' or name.startswith('gsd-') or 'gsd-' in name or name.startswith('.gsd') or name in ('super.md', 'copilotsuper.md') or name.startswith('superpowers'))
      if not is_allowed:
        try:
          os.remove(filepath)
        except Exception:
          pass
        continue

      try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
          content = f.read()
        new_content = content
        for pat, repl in subs:
          new_content = pat.sub(repl, new_content)
        if not root.startswith('workflows'):
          new_content = mvp_sub[0].sub(mvp_sub[1], new_content)
        if new_content != content:
          with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
      except Exception:
        pass
    for sub in dirs_list:
      subpath = os.path.join(root, sub)
      try:
        if not os.listdir(subpath):
          os.rmdir(subpath)
      except Exception:
        pass
"
ok "Filters & redactions applied"

# ── Hardcoded path scan ──────────────────────────────────────────────────────
echo "▶ Scanning for leaked paths..."
LEAKED=$(grep -rl \
  --include='*.md' --include='*.py' --include='*.sh' --include='*.yml' --include='*.yaml' \
  -e '$HOME' -e 'jleechantest@gmail' \
  .claude orchestration automation ralph workflows hermes 2>/dev/null \
  | grep -v exportcommands || true)
if [[ -n "$LEAKED" ]]; then
  warn "Hardcoded paths found — check filter list:"
  echo "$LEAKED" | sed 's/^/     /'
fi

# ── Update README via Claude CLI (preserve existing, update changelog only) ──
echo "▶ Updating README.md via Claude..."

# Capture diff stat BEFORE git add so we know what changed vs previous state
DIFF_STAT=$(git diff --stat 2>/dev/null || true)
NEW_FILES=$(git status --short 2>/dev/null | grep '^?' | awk '{print $2}' | head -20 || true)

if command -v claude >/dev/null 2>&1 && [[ -f "README.md" ]]; then
  EXISTING_README=$(cat README.md)
  COMMANDS_COUNT=$(find .claude/commands -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  SKILLS_COUNT=$(find .claude/skills -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  compute_hermes_counts
  README_LINE_COUNT=$(wc -l < README.md | tr -d ' ')

  # Validate README looks like real markdown (not a corrupt script-output file).
  # Real READMEs start with '---' (frontmatter) or '#' (heading) and have >20 lines.
  README_FIRST_LINE=$(head -1 README.md)
  README_IS_VALID=false
  if [[ "$README_FIRST_LINE" == "---"* || "$README_FIRST_LINE" == "#"* ]] && [[ "$README_LINE_COUNT" -gt 20 ]]; then
    README_IS_VALID=true
  fi

  if [[ "$README_IS_VALID" == "false" ]]; then
    warn "README.md appears corrupted (starts with: '${README_FIRST_LINE:0:60}', $README_LINE_COUNT lines) — skipping Claude update, keeping existing file"
    EXISTING_README=""
  fi

  README_PROMPT="You are updating the README for the jleechanorg/claude-commands GitHub repository.

Here is the EXISTING README (preserve all text except what needs updating):
---
${EXISTING_README}
---

Here is what changed in this export (git diff --stat):
${DIFF_STAT:-No file changes detected}

New files added this export:
${NEW_FILES:-None}

Current counts: ${COMMANDS_COUNT} commands, ${SKILLS_COUNT} skill files, ${HERMES_COMMANDS_COUNT} hermes commands, ${HERMES_SKILLS_COUNT} hermes skills.

TASK — make MINIMAL updates only:
1. Add or update a ## Changelog section near the top with today's date ($(date +%Y-%m-%d)) listing new/changed files briefly
2. If new slash commands appear in the diff that are not already mentioned in the README, add a one-line entry for each in the relevant section
3. Update any command/file counts if they changed significantly
4. Preserve ALL other text EXACTLY as-is — do not rewrite, reformat, or rephrase anything else

Output ONLY the updated markdown. No preamble, no explanation, no code fences."

  if [[ "$README_IS_VALID" == "false" ]]; then
    : # Skip Claude update — already warned above
  else
    # Write prompt to temp file to avoid shell quoting issues with large README content
    PROMPT_FILE=$(mktemp /tmp/exportcommands_prompt.XXXXXX)
    printf '%s' "$README_PROMPT" > "$PROMPT_FILE"
    # Run claude with --tools "" to disable all tools (forces plain text stdout, no Write tool).
    # Also run from a neutral temp dir (no CLAUDE.md) to prevent hook corruption of output.
    CLAUDE_NEUTRAL_DIR=$(mktemp -d /tmp/exportcommands_neutral.XXXXXX)
    # Always generate README.md.new for preview; only overwrite README.md in non-dry-run
    (cd "$CLAUDE_NEUTRAL_DIR" && timeout 30s claude --tools "" -p "$(cat "$PROMPT_FILE")") > README.md.new 2>/dev/null \
      || { rm -f README.md.new; echo "  ⚠️ Claude CLI failed/timed out — keeping existing README unchanged"; }
    rm -rf "$CLAUDE_NEUTRAL_DIR"
    rm -f "$PROMPT_FILE"
    if [[ -f "README.md.new" ]]; then
      if [[ "$DRY_RUN" == "false" ]]; then
        mv README.md.new README.md
        ok "README.md updated (changelog + new commands only)"
      else
        ok "README.md.new generated for preview (dry-run — not overwriting README.md)"
      fi
    fi
  fi  # end README_IS_VALID check

elif command -v claude >/dev/null 2>&1 && [[ ! -f "README.md" ]]; then
  # No existing README — generate fresh one (first-time export)
  COMMANDS_COUNT=$(find .claude/commands -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  SKILLS_COUNT=$(find .claude/skills -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  compute_hermes_counts
  HOOKS_COUNT=$(find .claude/hooks \( -name '*.sh' -o -name '*.py' \) 2>/dev/null | wc -l | tr -d ' ')

  README_PROMPT="Generate a concise README.md for the jleechanorg/claude-commands GitHub repository.
- 1-sentence description: reference export of a Claude Code CLI configuration
- Contains: ${COMMANDS_COUNT} slash commands, ${SKILLS_COUNT} skill files, ${HOOKS_COUNT} hooks, ${HERMES_COMMANDS_COUNT} hermes commands, ${HERMES_SKILLS_COUNT} hermes skills
- Quick Start: copy .claude/ dirs or run bash ~/.claude/commands/exportcommands.sh
- Directory overview: .claude/commands/, .claude/skills/, .claude/hooks/, .claude/agents/, .claude/scripts/, hermes/skills/, hermes/commands/
- List 6-8 useful commands: /pr, /copilot, /tdd, /harness, /exportcommands, /fixpr, /orch, /converge
- Include ## Changelog section with entry for $(date +%Y-%m-%d): initial export
- Under 120 lines, GitHub-flavored markdown
- Output ONLY the markdown, no preamble"

  CLAUDE_NEUTRAL_DIR=$(mktemp -d /tmp/exportcommands_neutral.XXXXXX)
  if [[ "$DRY_RUN" == "false" ]]; then
    (cd "$CLAUDE_NEUTRAL_DIR" && claude --tools "" -p "$README_PROMPT") > README.md 2>/dev/null \
      && ok "README.md created (first export)" \
      || warn "Claude CLI failed — no README generated"
  else
    (cd "$CLAUDE_NEUTRAL_DIR" && claude --tools "" -p "$README_PROMPT") > README.md.new 2>/dev/null \
      && ok "README.md.new generated for preview (dry-run)" \
      || warn "Claude CLI failed — no README preview generated"
  fi
  rm -rf "$CLAUDE_NEUTRAL_DIR"
else
  warn "Skipping README update (claude CLI not found)"
fi

# ── Contract Test Sync & Verification ───────────────────────────────────────
if [[ -f "tests/test_swarm_references.py" ]]; then
  python3 -c "
import re
with open('tests/test_swarm_references.py', 'r') as f:
    code = f.read()
if '\"/harness\"' not in code:
    code = code.replace('REFERENCED_COMMANDS = {', 'REFERENCED_COMMANDS = {\n    \"/harness\": \"harness.md\",')
    with open('tests/test_swarm_references.py', 'w') as f:
        f.write(code)
"
fi

if [[ -d "tests" ]]; then
  echo "▶ Running contract tests..."
  python3 -m unittest discover -s tests -p "test_*.py" || {
    warn "Contract tests failed! Fix errors before committing/pushing."
    exit 1
  }
  ok "Contract tests passed"
fi

# ── Commit & push ────────────────────────────────────────────────────────────
git add -A

if git diff --cached --quiet; then
  echo "No changes detected — nothing to export."
  exit 0
fi

CHANGED=$(git diff --cached --stat | tail -1)
git commit -m "export: $(date +%Y-%m-%d) — $CHANGED"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "DRY RUN — skipping push and PR creation."
  echo "Branch: $BRANCH | Repo: $REPO_DIR"
  exit 0
fi

git push -u origin "$BRANCH"

PR_STDERR=$(mktemp /tmp/exportcommands_pr_err.XXXXXX)
PR_URL=$(gh api repos/"$TARGET_REPO"/pulls --method POST \
  -f title="Claude Commands Export $(date +%Y-%m-%d)" \
  -f head="$BRANCH" \
  -f base="main" \
  -f body="Automated export. Source files overwrite target; target-only files preserved.

Changed: $CHANGED" \
  --jq '.html_url' 2>"$PR_STDERR") || {
    warn "PR creation failed: $(cat "$PR_STDERR")"
    rm -f "$PR_STDERR"
    exit 1
  }
rm -f "$PR_STDERR"

echo ""
echo "✅ Export complete!"
echo "   PR: $PR_URL"
echo "   Branch: $BRANCH"
